### ISSUE TITLE
Support for `async` evaluations

### ISSUE THREAD

**Issue by maxwellpeterson-wf** [dart-lang/boolean_selector#34]
I'd like to use this library, but in some cases, depending on the variable, I must make an asynchronous call to determine the value to return.

Would you be open to changing the typedef from:
```dart
bool Function(String variable)
```

to something like:
```dart
FutureOr<bool> Function(String variable)
```

This would enable the following contrived example usage:
```dart
selector.evaluate((variable) async {
  bool result = false;
  if (variable == 'special') {
    result = await someService.getValue();
  }
  return result;
});
```

**Comment by maxwellpeterson-wf** [comment]
@kevmoo FYI

**Comment by kevmoo** [comment]
My guess is that we won't be able to do this. I'd expect most uses of this package are sync. We wouldn't want to introduce async behavior here.

CC @grouma

**Comment by grouma** [comment]
I don't have much insight into this package other than the fact that it's used by `package:test`. @natebosch has a better understanding of this one.

**Comment by maxwellpeterson-wf** [comment]
We figured out a way to accomplish this without changing this package. Rough solution for posterity:

```dart
final bs = BooleanSelector.parse('a || b');
final vars = bs.variables.toList();
final answers = <String, bool>{};

final futures = vars.map((variable) {
  return getValue(variable).then((value) => answers[variable] = value);
});
await Future.wait(futures);

print(bs.evaluate((variable) => answers[variable]));
```

Where `getValue` is a function accepting a String and returning a `Future<bool>`.
